name: CI - Flask Redis App

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose version

    - name: Build and run containers
      run: docker-compose up --build -d

    - name: Wait for services to be ready
      run: |
        for i in {1..10}; do
        response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/health)
        if [ "$response" == "200" ]; then
            echo "App is healthy!"
            exit 0
        fi
        echo "Waiting for app... (attempt $i)"
        sleep 3
        done

        echo "Health check failed after 10 attempts"
        exit 1

    - name: Shut down
      run: docker-compose down

    - name: Show logs
      if: failure()
      run: docker-compose logs